
[tier-mk1]
	#Modifies the processing time of taking to process a resource: 0 being no speed modifier and 1 being a single tick per resource
	#The way this works is by taking the processing time from the soil and crop, then dividing it by the value given here. 0 being 0% and 1 being 100%
	#Range: 0.0 ~ 1.0
	speedModifier = 0.2
	#How much energy the pot will hold
	#Range: > 0
	maxEnergy = 1000000
	#Energy consumed per tick
	#Range: > 0
	perTickEnergy = 50000
	#Amount of items outputted per operation
	#Range: 1 ~ 1728
	itemsPerOutput = 16

[tier-mk2]
	#Modifies the processing time of taking to process a resource: 0 being no speed modifier and 1 being a single tick per resource
	#The way this works is by taking the processing time from the soil and crop, then dividing it by the value given here. 0 being 0% and 1 being 100%
	#Range: 0.0 ~ 1.0
	speedModifier = 0.4
	#How much energy the pot will hold
	#Range: > 0
	maxEnergy = 1000000
	#Energy consumed per tick
	#Range: > 0
	perTickEnergy = 115000
	#Amount of items outputted per operation
	#Range: 1 ~ 1728
	itemsPerOutput = 32

[tier-mk3]
	#Modifies the processing time of taking to process a resource: 0 being no speed modifier and 1 being a single tick per resource
	#The way this works is by taking the processing time from the soil and crop, then dividing it by the value given here. 0 being 0% and 1 being 100%
	#Range: 0.0 ~ 1.0
	speedModifier = 0.6
	#How much energy the pot will hold
	#Range: > 0
	maxEnergy = 2000000
	#Energy consumed per tick
	#Range: > 0
	perTickEnergy = 185000
	#Amount of items outputted per operation
	#Range: 1 ~ 1728
	itemsPerOutput = 48

[tier-mk4]
	#Modifies the processing time of taking to process a resource: 0 being no speed modifier and 1 being a single tick per resource
	#The way this works is by taking the processing time from the soil and crop, then dividing it by the value given here. 0 being 0% and 1 being 100%
	#Range: 0.0 ~ 1.0
	speedModifier = 0.8
	#How much energy the pot will hold
	#Range: > 0
	maxEnergy = 2000000
	#Energy consumed per tick
	#Range: > 0
	perTickEnergy = 350000
	#Amount of items outputted per operation
	#Range: 1 ~ 1728
	itemsPerOutput = 64

