
[general]
	enableMultiplayer = true
	#Enables a 5 minute timeout on the `ftbteamislands create` command
	creationTimeout = true
	clearInvWhenTeamLeft = true
	targetIslandLevel = "minecraft:overworld"
	enableSingleplayer = true
	enableMyIslandCommand = true

[lobby]
	#Auto-teleports player to their island once they join a team.
	autoTeleportToIsland = true
	#The lobby island spawned automatically on servers.
	#Must be resource location and within the structures folder of data
	lobbyStructureFile = "ftbteamislands:default_lobby"

[islands]
	#The default island.
	#Must be resource location and within the structures folder of data
	defaultIslands = "ftbteamislands:island"
	#Radius of the chunks to automatically claim if FTB Chunks is installed.
	#-1 = disabled
	#0 = 1x1
	#1 = 3x3
	#4 = 9x9
	#Range: -1 ~ 100
	autoClaimChunkRadius = 2
	#Distance put between new islands in regions, 1 being a single region
	#Range: 3 ~ 100
	distanceBetweenIslandsInRegions = 9
	#The default islands spawning Y offset
	#Range: > -2147483648
	defaultIslandResourceYOffset = -18
	#Allow selection of the island type, if set to false, then islands will be randomized.
	selectIslands = true
	#Height at which the islands will generate.
	#-1 = auto, on top of highest block in world
	#Range: -1 ~ 255
	height = 117

