
#General settings
[general]
	#Chance of bonemeal effect
	#0 being never and 1.0 being most of the time
	#Range: 0.0 ~ 1.0
	chance = 0.5
	#Enable debug logging
	debug = false
	#Use whitelist instead of blacklist
	useWhitelist = true
	#Range for bonemeal effect
	#Range: 0 ~ 16
	range = 3
	#List of blocks to blacklist from twerking
	#Tags can be used by using #minecraft:<tag_name> or #modid:<tag_name>
	blacklist = []
	#Enable mystical crops
	enableMysticalCrops = false
	#If useWhitelist is true use, only allow twerking the list below
	#Tags can be used by using #minecraft:<tag_name> or #modid:<tag_name>
	whitelist = ["#forge:sapling", "#minecraft:saplings", "minecraft:bamboo_sapling", "minecraft:bamboo"]
	#Enables OP mode!
	#Enable at your own risk
	opMode = false

